#!/bin/bash
#
# /etc/rc.d/init.d/sinatra
#
# chkconfig: - 80 20
# description: sinatra
# processname: sinatra
# pidfile: /var/run/sinatra/$prog.pid
#
### BEGIN INIT INFO
# Provides:          sinatra
# Default-Stop:      0 1 6
# Required-Start:    $local_fs
# Required-Stop:     $local_fs
# Short-Description: sinatra's init script
# Description:       sinatra is a rack application
### END INIT INFO

# Source function library.
. /etc/init.d/functions

name="sinatra-application-name"
prog="sinatra-application"

[ -f /etc/sysconfig/$prog ] && . /etc/sysconfig/$prog

USER=sinatra
GROUP=sinatra
PID_FILE=/var/run/sinatra/$PROG.pid
APP_DIR=/opt/sinatra
WEBAPPSDIR="$APP_DIR/$prog"
CONFIG_RU="$WEBAPPSDIR/config.ru"

if [ -n "${PIDFILE}" ]; then
        mkdir -p $(dirname ${PIDFILE})
        chown -R sinatra:sinatra $(dirname ${PIDFILE})
fi

export PATH=$PATH:/usr/lib/fluent/ruby/bin
RETVAL=0

start() {
        echo -n $"Starting $prog: "
        ARGS="$CONFIG_RU -D -I $WEBAPPSDIR -P $PID_FILE"
        su -c "rackup $ARGS" $USER
        RETVAL=$?
        echo
        [ $RETVAL = 0 ] && touch /var/lock/subsys/$prog
        return $RETVAL
}

stop() {
        echo -n $"Stopping $prog: "
        if [ -f $PID_FILE ];
        then
            # send interupt.
            kill -INT `cat $PID_FILE`
            RETVAL=$?
            echo
            [ $RETVAL = 0 ] && rm -f /var/lock/subsys/$prog $PID_FILE
            return $RETVAL
        else
            echo "pid file for $APP_DIR was not found : [$PID_FILE]"
            exit 1
        fi
}

restart() {
        stop
        start
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart)
        restart
        ;;

    *)
        echo "Usage: $prog {start|stop|restart}"
        exit 1
        ;;
esac
exit $?